// Serene ESLint config (flat, ESLint 9) — added 2026-07-02.
//
// Philosophy: CORRECTNESS AS ERRORS, STYLE STAYS OFF. TypeScript strict mode and
// check-tokens already guard types and design tokens; this config adds the two
// things they cannot see — React hooks correctness and the house rules from the
// CLAUDE.md Never-Do list, turned from documentation into machine-enforced law.
// Keep it lean: before adding a rule, ask what bug it prevents.
//
// Lint runs in the editor and via `pnpm lint` only — it is deliberately NOT wired
// into `pnpm build`, so build time is unchanged.

// eslint-config-next@16 ships flat-native presets — imported directly, no FlatCompat.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

// Rule 05: only src/lib/supabase/* may touch the Supabase packages (client
// instantiation points). Type-only imports are fine anywhere — a type cannot
// instantiate a client.
const SUPABASE_RESTRICTED_PATHS = [
  {
    name: '@supabase/ssr',
    message: 'Rule 05 — only src/lib/supabase/* instantiates Supabase clients.',
    allowTypeImports: true,
  },
  {
    name: '@supabase/supabase-js',
    message: 'Rule 05 — only src/lib/supabase/* instantiates Supabase clients.',
    allowTypeImports: true,
  },
];

// Provider-neutrality: adapters/anthropic.ts is the ONLY file allowed to import
// the Anthropic SDK (src/lib/elaya/CLAUDE.md).
const ANTHROPIC_RESTRICTED_PATH = {
  name: '@anthropic-ai/sdk',
  message: 'Only src/lib/elaya/adapters/anthropic.ts may import the Anthropic SDK.',
  allowTypeImports: false,
};

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'node_modules/**',
      'public/**',            // sw.js is hand-written vanilla JS for the SW runtime
      'graphify-out/**',
      'docs/**',
      'supabase/**',
      'scripts/**',           // one-off import/test scripts, run manually via tsx
      'next-env.d.ts',
      'src/lib/types/database.ts', // auto-generated by supabase gen types
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      // ── Correctness (errors) ─────────────────────────────────────────────
      // The stale-closure class of bug (the silent notification chime).
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'error',

      // react-hooks v7 ships React-Compiler-preparation rules that flag
      // deliberate, documented Serene patterns (usePortalAnchor render reads,
      // the localStorage post-mount hydration setState convention) as errors.
      // This codebase does not use the React Compiler — OFF until it does;
      // revisit the whole block on compiler adoption.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/static-components': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/incompatible-library': 'off',

      // Unused code hygiene — what the 2026-07 audit did by hand.
      // `_`-prefixed args are the codebase's deliberate-ignore convention.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],

      // ── House rules (the Never-Do list, machine-enforced) ────────────────
      // A-17: LazyMotion strict mode throws on the bare namespace in dev; the
      // linter catches it at write time instead.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'framer-motion',
              importNames: ['motion'],
              message: "A-17 — import { m as motion } from 'framer-motion' (LazyMotion strict).",
            },
          ],
        },
      ],
      // Never window.confirm/alert — compose <ConfirmDialog> / the toast system.
      'no-restricted-globals': [
        'error',
        { name: 'confirm', message: 'Compose <ConfirmDialog> — never window.confirm.' },
        { name: 'alert', message: 'Use the toast system — never window.alert.' },
      ],
      'no-restricted-properties': [
        'error',
        { object: 'window', property: 'confirm', message: 'Compose <ConfirmDialog> — never window.confirm.' },
        { object: 'window', property: 'alert', message: 'Use the toast system — never window.alert.' },
      ],

      // ── Deliberately relaxed (documented, not forgotten) ─────────────────
      // Sanctioned `as any` sites carry eslint-disable comments (the interim
      // pending-types-regen convention). Raw ones surface as warnings so they
      // are visible without blocking; tighten to 'error' after the next
      // `supabase gen types` regen retires the interim casts.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Copy like "That's everything." is fine in JSX — escaping apostrophes
      // in UI text is churn without a bug.
      'react/no-unescaped-entities': 'off',
      // WhatsApp media thumbnails render short-lived SIGNED urls — next/image's
      // loader/cache pipeline does not fit them. <img> there is deliberate.
      '@next/next/no-img-element': 'off',
    },
  },

  // Rule 05 + provider-neutrality scoping (everything except the sanctioned homes).
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/supabase/**'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { paths: [...SUPABASE_RESTRICTED_PATHS, ANTHROPIC_RESTRICTED_PATH] },
      ],
    },
  },
  // The Anthropic adapter keeps the supabase restriction but may import the SDK.
  {
    files: ['src/lib/elaya/adapters/anthropic.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { paths: SUPABASE_RESTRICTED_PATHS },
      ],
    },
  },
];

export default eslintConfig;
