// Serene ESLint config (flat, ESLint 9) — added 2026-07-02.
//
// Philosophy: CORRECTNESS AS ERRORS, STYLE STAYS OFF. TypeScript strict mode and
// check-tokens already guard types and design tokens; this config adds the two
// things they cannot see — React hooks correctness and the house rules from the
// CLAUDE.md Never-Do list, turned from documentation into machine-enforced law.
// Keep it lean: before adding a rule, ask what bug it prevents.
//
// Lint runs in the editor and via `pnpm lint` only — it is deliberately NOT wired
// into `pnpm build`, so build time is unchanged.

// eslint-config-next@16 ships flat-native presets — imported directly, no FlatCompat.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

// Rule 05: only src/lib/supabase/* may touch the Supabase packages (client
// instantiation points). Type-only imports are fine anywhere — a type cannot
// instantiate a client.
const SUPABASE_RESTRICTED_PATHS = [
  {
    name: '@supabase/ssr',
    message: 'Rule 05 — only src/lib/supabase/* instantiates Supabase clients.',
    allowTypeImports: true,
  },
  {
    name: '@supabase/supabase-js',
    message: 'Rule 05 — only src/lib/supabase/* instantiates Supabase clients.',
    allowTypeImports: true,
  },
];

// Provider-neutrality: adapters/anthropic.ts is the ONLY file allowed to import
// the Anthropic SDK (src/lib/elaya/CLAUDE.md).
const ANTHROPIC_RESTRICTED_PATH = {
  name: '@anthropic-ai/sdk',
  message: 'Only src/lib/elaya/adapters/anthropic.ts may import the Anthropic SDK.',
  allowTypeImports: false,
};

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'node_modules/**',
      'public/**',            // sw.js is hand-written vanilla JS for the SW runtime
      'graphify-out/**',
      'cleint-data/**',       // the founder's data folder: Atlas + app codebase copies, PII exports
      'docs/**',
      'supabase/**',
      'scripts/**',           // one-off import/test scripts, run manually via tsx
      'connector/**',         // the Sia Baileys watcher — its own Node package + tsconfig (connector/tsconfig.json); not part of the Next.js app lint scope
      'backend/**',           // the Python backend (master-plan Step 2) — not TS/JS app code
      'evals/**',             // the Python eval harness — not TS/JS app code
      'design_handoff_neumorphic_system/**', // design-reference bundle (HTML specimens + their runtime), never shipped
      'design_handoff_dark_mode/**',         // same — the dark-mode specimen + its generated support.js runtime
      'design_handoff_mobile_system/**',     // same — the mobile-system specimen bundle
      'designss/**',                          // archived design-reference bundles (same generated runtimes)
      'next-env.d.ts',
      'src/lib/types/database.ts', // auto-generated by supabase gen types
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      // ── Correctness (errors) ─────────────────────────────────────────────
      // The stale-closure class of bug (the silent notification chime).
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'error',

      // react-hooks v7 ships React-Compiler-preparation rules that flag
      // deliberate, documented Serene patterns (usePortalAnchor render reads,
      // the localStorage post-mount hydration setState convention) as errors.
      // This codebase does not use the React Compiler — OFF until it does;
      // revisit the whole block on compiler adoption.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/static-components': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/incompatible-library': 'off',

      // Unused code hygiene — what the 2026-07 audit did by hand.
      // `_`-prefixed args are the codebase's deliberate-ignore convention.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],

      // ── House rules (the Never-Do list, machine-enforced) ────────────────
      // A-17: LazyMotion strict mode throws on the bare namespace in dev; the
      // linter catches it at write time instead.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'framer-motion',
              importNames: ['motion'],
              message: "A-17 — import { m as motion } from 'framer-motion' (LazyMotion strict).",
            },
          ],
        },
      ],
      // Never window.confirm/alert — compose <ConfirmDialog> / the toast system.
      'no-restricted-globals': [
        'error',
        { name: 'confirm', message: 'Compose <ConfirmDialog> — never window.confirm.' },
        { name: 'alert', message: 'Use the toast system — never window.alert.' },
      ],
      'no-restricted-properties': [
        'error',
        { object: 'window', property: 'confirm', message: 'Compose <ConfirmDialog> — never window.confirm.' },
        { object: 'window', property: 'alert', message: 'Use the toast system — never window.alert.' },
      ],

      // ── Deliberately relaxed (documented, not forgotten) ─────────────────
      // Sanctioned `as any` sites carry eslint-disable comments (the interim
      // pending-types-regen convention). Raw ones surface as warnings so they
      // are visible without blocking; tighten to 'error' after the next
      // `supabase gen types` regen retires the interim casts.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Copy like "That's everything." is fine in JSX — escaping apostrophes
      // in UI text is churn without a bug.
      'react/no-unescaped-entities': 'off',
      // WhatsApp media thumbnails render short-lived SIGNED urls — next/image's
      // loader/cache pipeline does not fit them. <img> there is deliberate.
      '@next/next/no-img-element': 'off',
    },
  },

  // Rule 05 + provider-neutrality scoping (everything except the sanctioned homes).
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/supabase/**'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { paths: [...SUPABASE_RESTRICTED_PATHS, ANTHROPIC_RESTRICTED_PATH] },
      ],
    },
  },
  // Schema restructure (2026-09-17, docs/architecture/schema-restructure-plan.md): a table
  // that moved out of `public` must be read through its schema helper (giaDb) — an
  // unscoped `.from('leads')` would hit public.leads, which no longer exists, at runtime.
  // The table list mirrors GIA_TABLES + MEMBER_TABLES in src/lib/supabase/schemas.ts. Receivers that pass:
  // giaDb(...), freshdeskDb(...), anything.schema(...).
  {
    files: ['src/**/*.{ts,tsx}'],
    // freshdesk-sync.ts reads the MIRROR's own `sla_policies` (schema freshdesk) through
    // freshdeskDb() held in a local — same name as the Gia table, different schema.
    ignores: ['src/lib/services/freshdesk-sync.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.property.name='from'][arguments.0.value=/^(members|member_access_log|member_anticipations|member_chunks|member_documents|member_events|member_facts|member_health_events|member_health_policy|member_people|member_relations|member_snapshot|leads|lead_activities|lead_notes|lead_raw_payloads|lead_sla_timers|lead_product_enquiries|deals|sla_policies|agent_routing_config|revival_candidates|revival_policies|domain_targets|ad_creatives|ad_spend_daily|ad_account_recharges|task_gia_meta|whatsapp_conversations|whatsapp_messages|whatsapp_conversation_reads|whatsapp_notification_logs|service_cases|conversation_hooks)$/]:not([callee.object.callee.name=/^(giaDb|memberDb|freshdeskDb)$/]):not([callee.object.callee.property.name='schema'])",
          message:
            'This table lives in the gia or member schema — query it through giaDb(client) / memberDb(client).from(…) (src/lib/supabase/schemas.ts), never an unscoped .from().',
        },
      ],
    },
  },
  // The Anthropic adapter keeps the supabase restriction but may import the SDK.
  {
    files: ['src/lib/elaya/adapters/anthropic.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { paths: SUPABASE_RESTRICTED_PATHS },
      ],
    },
  },
];

export default eslintConfig;
